In [1]:
import spacy
from spacy import displacy
from collections import Counter
import en_core_web_sm
nlp = en_core_web_sm.load()

In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/PC/Desktop/INFO YA BEHI/AI/PCD/nv/version Finale/Data Scicence Part/data final/data4.csv")
#a=d2.drop_duplicates()
df.head()

,Scholarship Name,Deadline,Amount,Offered by,Eligibility,Description,Link
0,American University Emerging Global Leader Sch...,December 15 2017,All billable expenses*,NaN,Student plans to improve under-resourced or un...,The American University (AU) Emerging Global L...,https://www.american.edu/admissions/internatio...
1,Clark University Global Scholars Program Schol...,February 1,$15000 - $25000/year*,NaN,First-year applicant to Clark UniversityShows ...,NaN,http://www.clarku.edu/scholarships-first-year-...
2,Academic Merit Scholarship,August 14 (fall) January 2 (spring),50% of out-of-state tuition + fees,NaN,Enrolled at East Tennessee State UniversityDem...,NaN,https://www.etsu.edu/honors/international/inte...
3,Illinois State University Redbird Academic Sch...,File for admission between September 1 and Nov...,$1000 - $4000/year,NaN,3.4 GPA (minimum) on 4.0 scale25 or higher ACT...,NaN,https://financialaid.illinoisstate.edu/scholar...
4,Lillian Kumata Scholarship Program,Fall semester applications due the last weekda...,$2500,NaN,Is a current married international student at ...,These need-based partial-tuition scholarships ...,http://cvip.isp.msu.edu/programs/lillian-kumat...

In [3]:
l=[]
for i in df['Amount']:
    l.append([X.text for X in nlp(str(i)).ents if (str(X.label_)=="MONEY")])

In [4]:
l

[[],
 ['15000', '25000'],
 [],
 ['1000', '4000'],
 ['2500'],
 [],
 [],
 [],
 [],
 ['7500', '30000'],
 ['5000'],
 ['1000'],
 ['2500'],
 ['5000'],
 ['1000'],
 ['3000'],
 [],
 [],
 ['1000', '10000'],
 ['1500'],
 ['Up to $1500']]

In [5]:

df2 = pd.read_csv("C:/Users/PC/Desktop/INFO YA BEHI/AI/PCD/nv/version Finale/Data Scicence Part/data5.csv")
#a=d2.drop_duplicates()
df2.head()

,Scholarship Name,SchoLevel,SchoValue,SchoDeadline,SchoStudyIn,Descriptions,Eligibility,Application,Website
0,Holland Government/Erasmus University Rotterdam,Bachelors/Masters Degree,NaN,1 Feb/1 May 2020 (Annual),Netherlands,The Erasmus University Holland Scholarship is ...,Applicants must be:â€¢ Non-EEA nationals who hav...,The application procedure differs per faculty....,https://www.eur.nl/en/education/practical-matt...
1,University of Sheffield,Masters Degree,NaN,6 May 2020,UK,"The University of Sheffield, in collaboration ...",NaN,You will be automatically considered for the s...,https://www.sheffield.ac.uk/international/fees...
2,10 April 2020 (annual),Japan,NaN,JFUNU,PhD Degree,The Japan Foundation for UNU (JFUNU) Scholarsh...,NaN,"To apply, you must complete the online applica...",https://ias.unu.edu/en/admissions/degrees/phd-...
3,15 Apr 2020 (annual),New Zealand,NaN,University of Canterbury,Bachelors Degree,The University of Canterbury offers the UC Int...,Eligible candidates must be full-fee-paying in...,Applications are done online. Deadline is 15 A...,http://www.canterbury.ac.nz/scholarshipsearch/...
4,1/15 April 2020 (annual),Netherlands,NaN,Rotary Foundation/UNESCO-IHE,Masters Degree,The Rotary Foundation and the UNESCO-IHE Insti...,Students eligible for this scholarship must be...,Students admitted to IHE Delft Institute for W...,https://www.un-ihe.org/rotary-scholarships-wat...

In [6]:
import pandas as pd
df3 = pd.read_csv("C:/Users/PC/Desktop/INFO YA BEHI/AI/PCD/nv/version Finale/Data Scicence Part/data final/data2.csv")
#a=d2.drop_duplicates()
df3.head()

,Scholarship Name,Deadline,Amount,Offered by,State,Descriptions,Essay Required,Recommendations Required,Minimum GPA,Major,Type,Link
0,$1000 Tallo & Niche Feelin&apos Lucky Scholarship,March 18 2020,$1000,Tallo,Nationwide,In honor of St. Patrick&aposs Day we&aposve pa...,No,No,None,Any Major,Generic,https://tallo.com/niche-scholarship/
1,$1000 Tallo&aposs Easy March Scholarship,March 31 2020,$1000,Tallo,Nationwide,Ready for the easiest $1000 scholarship you&ap...,No,No,None,Any Major,Generic,https://app.tallo.com/register?promoCode=NICHE...
2,$1000 Easy Scholarship: Answer Student Debt Qu...,March 31 2020,$1000,DoSomething,Nationwide,You could win an easy $1000 scholarship by ano...,No,No,None,Any Major,Generic,https://www.dosomething.org/us/campaigns/compa...
3,Review Your School $1000 Scholarship,March 31 2020,$1000,Niche,Nationwide,Take a short survey about your school for a ch...,No,No,None,Any Major,Generic,https://www.niche.com/k12/school-survey-sweeps...
4,ScholarshipPoints $1000 Scholarship,March 31 2020,$1000,Scholarship Points,Nationwide,ScholarshipPoints.com will give away over $100...,No,No,None,Any Major,Generic,http://tracking.edvisors.com/aff_c?offer_id=11...

In [7]:
ll=[]
for i in df['Amount']:
    ll.append([X.text for X in nlp(str(i)).ents if (str(X.label_)=="MONEY")])

In [8]:
df['Amount']

0                           All billable expenses*
1                            $15000 - $25000/year*
2               50% of out-of-state tuition + fees
3                               $1000 - $4000/year
4                                            $2500
5                           Full tuition + stipend
6            Tuition + room and board for one year
7                               $500 - $10000/year
8                                   Tuition costs*
9                              $7500 - $30000/year
10                                           $5000
11                                           $1000
12                                           $2500
13                                           $5000
14                                           $1000
15                                           $3000
16    Tuition airfare stipend and health insurance
17                  Tuition travel and other costs
18                                  $1000 - $10000
19                                           $1500
20                                     Up to $1500
Name: Amount, dtype: object

In [9]:
ll

[[],
 ['15000', '25000'],
 [],
 ['1000', '4000'],
 ['2500'],
 [],
 [],
 [],
 [],
 ['7500', '30000'],
 ['5000'],
 ['1000'],
 ['2500'],
 ['5000'],
 ['1000'],
 ['3000'],
 [],
 [],
 ['1000', '10000'],
 ['1500'],
 ['Up to $1500']]

In [11]:
df01=pd.read_csv('C:/Users/PC/Desktop/INFO YA BEHI/AI/PCD/nv/version Finale/Data Scicence Part/data final/data1.csv')
df01.head()

,Scholarship Name,Level of Study,Scholarship Value,Date,Eligibility,Benefits,Application,Descriptions,Link
0,2020 Mixed Martial Arts Scholarship by MiddleE...,Bachelor Course,$900,15 November 2020,Any high school senior or college/university s...,The winner will receive 900$ in scholarship pr...,Each applicant must submit a video of them spe...,Here at MiddleEasy.com we value the importance...,https://middleeasy.com/scholarships/
1,2020 Fitness and Educational Scholarship,Bachelor Course,$1000,15 November 2020,Our scholarship is open to all college student...,The selected student will receiveÂ $1000 Schola...,Eligible applicants are required to submit a 1...,FitnessVolt.com is happy to announce a yearly ...,https://fitnessvolt.com/scholarship/
2,The Katoni scholarship - Supporting cultural p...,Master Bachelor Phd,DKK 10000,1 May 2020,The scholarship is given to researchers studen...,The Katoni scholarship is given annually to on...,What to include in your application:Full nameA...,The Katoni scholarship is given annually to on...,https://www.katoni.dk/scholarship/
3,Writing Contest Scholarship 2020,Master Bachelor Phd Course,2000$,31 May 2020,We invite graduate and undergraduate high scho...,Our three winners will get cash prizes. Plus t...,Make sure you have discovered our rules before...,One of our goals is to motivate students to im...,https://admission-writer.com/blog/scholarship
4,Greg Baumgartner Scholarship,Bachelor Course,$1000,31 August 2020,Applicants must be enrolled in either high sch...,one winner will receive $1000 scholarshipÂ money,To apply please write a very short essay (not ...,The importance of education cannot be overstat...,NaN

In [12]:
df01['Scholarship Value']

0                                                    $900
1                                                   $1000
2                                               DKK 10000
3                                                   2000$
4                                                   $1000
5       56% of semester tution - An equivalent of 7500...
6                       $1000 (1 winner) $250 (2 winners)
7                                                   $2000
8                                                   $2500
9                                         Â£10000 - Â£44000
10                                                  $1000
11                                                  $1000
12                                           US $25000.00
13                                                  $1000
14                                                  $1000
15                                                   $500
16                                                  $1000
17                                                   $500
18                                                 Â£15009
19                                                  $5000
20                                                   1000
21       $1000 to $8000 per year at eligible universities
22              Multiple Scholarships from $1000 to $5000
23                       25% to 100% off total GMAT prep.
24                                                  $1000
25                                                   $500
26                                                  $1000
27                                                  $1000
28                20% of tuition fee up to $2000 per year
29                                                  $1000
                              ...
1036                                         Fully Funded
1037                                           Not Funded
1038                                     Partially Funded
1039                                         Fully Funded
1040                                     Partially Funded
1041                                         Fully Funded
1042                                         Fully Funded
1043                                     Partially Funded
1044                                     Partially Funded
1045                                     Partially Funded
1046                                     Partially Funded
1047                                     Partially Funded
1048                                         Fully Funded
1049                                     Partially Funded
1050                                         Fully Funded
1051                                         Fully Funded
1052                                     Partially Funded
1053                                     Partially Funded
1054                                     Partially Funded
1055                                         Fully Funded
1056                                         Fully Funded
1057                                         Fully Funded
1058                                         Fully Funded
1059                                         Fully Funded
1060                                         Fully Funded
1061                                     Partially Funded
1062                                          Tuition fee
1063                                              â‚¬ 2000-
1064                                     27 November 2016
1065           Tuition fee living costs medical insurance
Name: Scholarship Value, Length: 1066, dtype: object

In [14]:
a=[]
for i in df01['Scholarship Value']:
    a.append([X.text for X in nlp(str(i)).ents if (str(X.label_)=="MONEY")])

In [15]:
a

[[],
 ['1000'],
 [],
 [],
 ['1000'],
 [],
 ['1000', '250'],
 ['2000'],
 ['2500'],
 [],
 ['1000'],
 ['1000'],
 ['25000.00'],
 ['1000'],
 ['1000'],
 ['500'],
 ['1000'],
 ['500'],
 [],
 ['5000'],
 [],
 ['1000', '8000'],
 ['1000', '5000'],
 [],
 ['1000'],
 ['500'],
 ['1000'],
 ['1000'],
 ['up to $2000'],
 ['1000'],
 [],
 ['1000'],
 ['500'],
 ['1000'],
 ['1000'],
 ['1000'],
 [],
 [],
 ['1000'],
 [],
 [],
 ['4000'],
 [],
 [],
 [],
 ['54000'],
 ['3000'],
 ['45000'],
 ['10000'],
 ['8000'],
 ['10000'],
 ['8000'],
 ['20.000'],
 [],
 ['10000'],
 ['68357'],
 ['44000'],
 ['2000'],
 [],
 ['15000'],
 ['22000'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['20000'],
 [],
 ['22000'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['1000'],
 [],
 ['1000'],
 [],
 [],
 [],
 ['5000'],
 [],
 ['3500'],
 ['500'],
 ['2000'],
 ['1000'],
 [],
 ['7000'],
 ['1500', '1000', '500'],
 ['1000'],
 ['1000'],
 [],
 ['4000'],
 ['1500.00'],
 ['1500'],
 ['1000', '1000'],
 ['1000'],
 ['1500'],
 ['1000'],
 ['1000'],
 ['25000'],
 ['2000'],
 ['Approximately $26000'],
 ['500'],
 ['55000'],
 ['50760'],
 [],
 [],
 [],
 [],
 ['1200'],
 ['2000'],
 [],
 ['more than $100000'],
 ['1000'],
 ['1500'],
 ['1500'],
 ['2500'],
 ['2000'],
 ['1000'],
 ['1000'],
 [],
 [],
 ['1000', '2000'],
 ['1000'],
 [],
 ['3000'],
 [],
 ['1500'],
 ['2000'],
 [],
 ['2000'],
 [],
 ['2000'],
 [],
 ['2000'],
 ['700'],
 [],
 [],
 ['2000'],
 [],
 ['500'],
 ['1000'],
 [],
 [],
 [],
 [],
 ['2000'],
 [],
 [],
 ['1500'],
 ['1000'],
 [],
 ['1000'],
 ['1000'],
 ['500'],
 [],
 ['2500'],
 ['500'],
 ['1000'],
 ['500'],
 [],
 ['2000'],
 ['1000'],
 ['500'],
 [],
 ['500'],
 ['1000', 'two $250'],
 [],
 ['2000'],
 ['450', '2000'],
 [],
 ['500'],
 ['5000'],
 ['1500'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['5000'],
 ['750'],
 ['1500'],
 [],
 ['2000'],
 [],
 ['1000'],
 ['1000'],
 [],
 ['1000'],
 ['6000'],
 ['500'],
 [],
 ['3000'],
 ['1000'],
 ['500'],
 ['1000'],
 ['1500'],
 ['1000'],
 ['2300'],
 [],
 ['4200'],
 ['up to $10000'],
 ['2500'],
 ['1000'],
 ['1000'],
 [],
 [],
 ['1000'],
 ['2500'],
 [],
 ['1000'],
 ['1000'],
 ['2000'],
 ['700'],
 ['500'],
 ['1000'],
 ['1000'],
 [],
 ['2999'],
 ['500'],
 ['3000'],
 ['1000'],
 ['500'],
 [],
 ['3800'],
 [],
 ['1000'],
 ['1000'],
 ['1000'],
 ['2500'],
 [],
 ['1000'],
 [],
 ['1000'],
 ['350'],
 ['1000'],
 ['750'],
 ['1000'],
 ['10000'],
 ['3000'],
 ['1500'],
 ['1500'],
 ['1000'],
 [],
 ['5750'],
 ['500'],
 ['1000'],
 ['15000'],
 [],
 ['1000'],
 ['2000'],
 [],
 ['1000'],
 [],
 ['1000'],
 ['500'],
 ['between $2001.00 and $50000.00'],
 ['1000'],
 [],
 ['500'],
 [],
 ['1000'],
 [],
 [],
 [],
 ['2000'],
 [],
 ['1000'],
 [],
 ['1000'],
 ['1000'],
 [],
 [],
 ['1000'],
 ['1500'],
 [],
 [],
 ['500'],
 ['3000'],
 ['750'],
 [],
 [],
 [],
 [],
 ['1500.00'],
 [],
 [],
 ['2000'],
 [],
 ['1000', '500', '250'],
 [],
 [],
 [],
 [],
 [],
 ['1000'],
 ['1000.00'],
 ['1000'],
 ['1000'],
 ['15000'],
 ['1000'],
 [],
 ['1000'],
 [],
 [],
 ['25000'],
 ['500'],
 ['3000'],
 ['1.000'],
 ['2000'],
 ['5000'],
 [],
 [],
 [],
 [],
 ['500'],
 ['1000'],
 [],
 ['1000'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['500'],
 [],
 ['1000'],
 [],
 [],
 [],
 ['10000'],
 ['between $2001.00 and $50000.00'],
 ['1000', '250'],
 [],
 [],
 [],
 ['1500$1000$500'],
 [],
 [],
 ['15000'],
 ['1000'],
 ['1000'],
 ['1000'],
 [],
 ['2000'],
 ['30000'],
 [],
 ['5000'],
 ['1000'],
 ['30000'],
 [],
 ['5000'],
 ['30000'],
 [],
 ['30000'],
 [],
 ['500'],
 ['1000', '250'],
 ['1 x $500 1 x $100'],
 ['4500'],
 ['1000.00'],
 ['1000'],
 [],
 [],
 [],
 [],
 ['2000'],
 ['3500'],
 ['60000'],
 ['100'],
 ['1000'],
 ['2500'],
 [],
 ['2000'],
 ['5000'],
 ['500'],
 ['1000'],
 ['500'],
 [],
 ['750'],
 ['1000'],
 ['1000'],
 ['1500.00'],
 ['2500'],
 ['1000'],
 [],
 ['1000'],
 ['2000'],
 ['1000'],
 ['2000', '1000'],
 [],
 [],
 ['2500'],
 ['1000'],
 ['1000'],
 ['1500'],
 [],
 ['3000'],
 [],
 ['1000.00'],
 ['1000.00'],
 ['3500'],
 [],
 ['$1000', '750', '500 $250'],
 [],
 ['3000', 'two $1000', 'two $500'],
 [],
 ['500'],
 ['1000'],
 ['1500'],
 ['500'],
 [],
 ['1000'],
 ['50000'],
 ['30000'],
 ['3000'],
 ['5000'],
 [],
 ['10000'],
 ['500'],
 ['1000'],
 [],
 ['500'],
 [],
 ['30000'],
 ['500.00'],
 ['500'],
 [],
 ['1000'],
 ['1000', '500'],
 [],
 ['1000'],
 ['1100', '400'],
 [],
 ['1000.00'],
 ['100'],
 ['1500'],
 ['500'],
 ['1000'],
 [],
 ['1000'],
 ['5000'],
 [],
 ['1000'],
 ['1000', '500'],
 ['1000'],
 ['10000'],
 [],
 ['30000'],
 [],
 ['500'],
 ['500'],
 ['750'],
 ['1000'],
 [],
 ['1500'],
 [],
 [],
 ['$1 Million'],
 [],
 ['20000'],
 ['30000'],
 ['3.000'],
 ['2000'],
 [],
 ['2500'],
 ['$1 Million'],
 ['30000'],
 ['10000'],
 ['$1 Million'],
 [],
 [],
 ['1000'],
 ['1000'],
 ['up to $2500'],
 ['3000'],
 [],
 [],
 ['500'],
 ['40000'],
 ['40000'],
 ['1000'],
 ['1000'],
 ['1500'],
 ['2500$  Second', '1500$ Third Prize', '1000$'],
 [],
 ['20000'],
 ['600$ 2-nd', '$ 3-rd - 200$'],
 ['600$ 2-nd', '$ 3-rd - 200$'],
 ['1000'],
 ['2000'],
 ['100'],
 ['$1000 $500 and $250'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['2500'],
 [],
 [],
 ['1500'],
 ['500'],
 ['1000'],
 ['5000'],
 ['1500'],
 [],
 ['550$'],
 ['10000'],
 ['1000'],
 [],
 ['2000', '1000', '500'],
 ['1000'],
 ['1000'],
 ['2500'],
 ['$1 Million'],
 ['60000'],
 ['2000'],
 [],
 ['up to $10000'],
 ['8000'],
 ['1500'],
 ['2000'],
 ['10000', 'up to $2000'],
 [],
 [],
 ['5000'],
 ['2500'],
 ['3200'],
 ['1500'],
 ['2500'],
 [],
 ['500'],
 ['1500'],
 [],
 ['30000'],
 ['22 $2018'],
 ['1500'],
 ['1000'],
 ['60000'],
 ['2000'],
 [],
 ['1000'],
 ['5000', '1000'],
 [],
 ['2000'],
 [],
 ['600'],
 [],
 ['1000'],
 [],
 [],
 ['5000'],
 ['200'],
 [],
 ['between $2000 - $7500'],
 [],
 ['3000'],
 ['1000'],
 ['2000', '10000'],
 ['10000'],
 ['30000'],
 ['1000'],
 ['8000'],
 [],
 ['500'],
 ['500'],
 ['between $2000 to $6000'],
 ['1572'],
 ['500'],
 [],
 ['1000', '1000', '500'],
 ['1000', '1000', '500'],
 ['2000'],
 [],
 ['35000'],
 ['30000'],
 ['10000'],
 ['1000'],
 ['10000'],
 ['2000'],
 ['30000'],
 ['2000', '10000'],
 ['1000'],
 ['10000'],
 ['30000'],
 [],
 ['500'],
 ['1.000'],
 ['15000'],
 [],
 ['10000'],
 ['$1000 $600 $400'],
 ['15000'],
 [],
 ['5000'],
 ['1500'],
 [],
 ['500'],
 ['5000'],
 ['1250'],
 ['1000', '8000'],
 ['250-$500'],
 ['1000'],
 [],
 ['1000'],
 ['up to $30000'],
 ['500'],
 [],
 [],
 ['1000'],
 ['1500'],
 ['400.00', '2000.00'],
 ['500'],
 ['5000'],
 ['2000'],
 ['1250'],
 [],
 ['27082'],
 ['Three $1000.00'],
 ['1500', '1000', '500'],
 ['1000'],
 [],
 [],
 ['500'],
 ['2000'],
 ['500'],
 ['500'],
 ['2000'],
 ['1000'],
 ['500'],
 ['1000'],
 ['30', '10000'],
 ['$500 dollars'],
 [],
 [],
 ['3000'],
 ['$500 dollars'],
 ['$500 dollars'],
 [],
 ['1.250'],
 [],
 ['1500'],
 ['2500'],
 ['500'],
 ['250'],
 ['2100'],
 ['1500'],
 [],
 ['1000'],
 ['1000 dollars'],
 ['2500'],
 ['1000'],
 ['500'],
 ['1000'],
 ['1500'],
 [],
 ['2000'],
 ['1500'],
 ['1500'],
 ['1000', '500'],
 [],
 ['1000'],
 [],
 [],
 [],
 [],
 ['5000'],
 ['1000'],
 ['1000'],
 ['37000'],
 ['37000'],
 ['3000'],
 ['1 x $25000', '5 x $5000'],
 ['5000'],
 ['1000'],
 ['1000'],
 ['20000'],
 ['1000'],
 [],
 [],
 ['3000'],
 ['1000$1500$2500'],
 ['$1000 dollars'],
 ['1000'],
 ['250', '1000'],
 ['3000'],
 ['750', '500', '350'],
 ['3000'],
 ['2000'],
 ['500'],
 ['1500'],
 ['20000'],
 [],
 [],
 ['1000'],
 ['1000'],
 ['1000'],
 ['3500'],
 ['500'],
 ['2000'],
 ['10000'],
 ['2500'],
 ['2500.00'],
 ['5000'],
 ['500'],
 ['1500'],
 ['200'],
 ['1000'],
 ['1000'],
 ['2000'],
 ['2000'],
 [],
 ['500'],
 ['1000'],
 ['1000'],
 ['500'],
 [],
 ['1000'],
 ['1000'],
 ['10000'],
 ['1000'],
 ['1200'],
 ['1000'],
 [],
 ['2000'],
 [],
 [],
 ['1000'],
 ['500'],
 ['3000'],
 [],
 ['1000'],
 ['1000'],
 ['2000'],
 ['1000'],
 ['500'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['2.000'],
 [],
 ['500'],
 ['2000'],
 [],
 ['300'],
 ['1000'],
 [],
 ['1000'],
 [],
 ['1000'],
 ['250'],
 ['500.00'],
 ['2999'],
 ['1800'],
 ['2000'],
 ['1236'],
 ['2000'],
 ['3000'],
 ['1.000'],
 ['1000'],
 ['500'],
 ['1000'],
 ['1500'],
 ['1500'],
 ['1000'],
 ['500'],
 [],
 ['500'],
 [],
 [],
 ['10000'],
 ['2000'],
 ['7.500'],
 ['1500'],
 ['1000'],
 ['3000'],
 ['500'],
 ['500$ 350$ 150$'],
 ['500'],
 ['1000'],
 ['1000'],
 ['Up to $1500'],
 ['10000'],
 ['1000'],
 ['1000'],
 ['1000'],
 [],
 ['1000'],
 ['20000'],
 ['1000'],
 [],
 ['5000'],
 ['1000'],
 ['1500'],
 ['1000'],
 ['2500'],
 ['1000'],
 [],
 ['2500'],
 ['2500'],
 ['40'],
 ['1.000'],
 ['3000'],
 ['1000'],
 ['1000'],
 ['5000'],
 [],
 [],
 [],
 ['1000'],
 ['1000'],
 ['3000'],
 ['2000'],
 ['1000'],
 ['3000'],
 ['1500'],
 ['3000'],
 ['1000'],
 ['1000'],
 ['5000'],
 ['1000'],
 ['500'],
 ['1000'],
 ['1000'],
 ['1500'],
 ['3099'],
 ['2000'],
 ['between $300-$500'],
 ['1000'],
 ['1300'],
 ['1000'],
 ['1000'],
 ['2549'],
 ['5000'],
 ['1000'],
 ['2500'],
 ['20.000'],
 ['1500'],
 ['10000'],
 ['1000'],
 ['1000'],
 [],
 [],
 ['3000'],
 ['2000'],
 ['5000'],
 ['5000'],
 ['3000'],
 ['1000'],
 ['1000'],
 ['1000'],
 ['1000'],
 [],
 [],
 [],
 [],
 ['2000'],
 [],
 [],
 ['15000'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['1000'],
 ['1000'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['1500'],
 ['500'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ...]

In [16]:
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

#Cleaning the Scholarship Value of Data1.csv
tokens_without_sw1=[]
for ch in Money1:
    word=word_tokenize(str(ch)) 
    tokens_without_sw1 += [[w for w in word if not w in stopwords.words('english')]]
for index,l in enumerate(tokens_without_sw1):
    a=[]
    for x in l:
        try:
            a.append(float(x))
        except:
            pass
    tokens_without_sw1[index]=a
    
#Money1=tokens_without_sw1     
        
print("Money1=",tokens_without_sw1,"\n")

#Cleaning the Scholarship Value of Data2.csv
tokens_without_sw2=[]
for ch in Money2:
    word=word_tokenize(str(ch)) 
    tokens_without_sw2 += [[w for w in word if not w in stopwords.words('english')]]
for index,l in enumerate(tokens_without_sw2):
    a=[]
    for x in l:
        try:
            a.append(float(x))
        except:
            pass
    tokens_without_sw2[index]=a
    
Money2=tokens_without_sw2     
        
print("Money2=",Money2,"\n")

#Cleaning the Scholarship Value of Data4.csv
tokens_without_sw4=[]
for ch in Money4:
    word=word_tokenize(str(ch)) 
    tokens_without_sw4 += [[w for w in word if not w in stopwords.words('english')]]
for index,l in enumerate(tokens_without_sw4):
    a=[]
    for x in l:
        try:
            a.append(float(x))
        except:
            pass
    tokens_without_sw4[index]=a
    
Money4=tokens_without_sw4     
        
print("Money4=",Money4,"\n")

NameError: name 'nltk' is not defined

In [18]:
s = "3andi 500$ wkifkif between $100 w 1500$ wyaateha triha tounes 3al $14555.2 wel 100.5$ wzeda hatta 303Â£ wm3ahom Â£10"

In [25]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('\w+|\$[\d\.]+|\S+')
Money1=[]
A=tokenizer.tokenize(s)
for i in A:
    Money1.append([X.text for X in nlp(str(i)).ents if (str(X.label_)=="MONEY")])

In [28]:
A

['3andi',
 '500',
 '$',
 'wkifkif',
 'between',
 '$100',
 'w',
 '1500',
 '$',
 'wyaateha',
 'triha',
 'tounes',
 '3al',
 '$14555.2',
 'wel',
 '100',
 '.5$',
 'wzeda',
 'hatta',
 '303',
 'Â£',
 'wm3ahom',
 'Â£10']